name: Build Zhuque Fangsong

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install fontmake
      run: |
        python -m pip install --upgrade pip
        pip install fontmake

    - name: Compile Glyphs to TTF
      run: |
        mkdir -p build
        fontmake -g src/ZhuqueFangsong.glyphspackage -o ttf --output-path build/ZhuqueFangsong.ttf

    - name: Upload Font
      uses: actions/upload-artifact@v7
      with:
        name: ZhuqueFangsong
        path: build/*